services:
    - type: web
      name: laravel-react-app
      env: docker
      region: ohio
      plan: free
      branch: main
      healthCheckPath: /
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_KEY
            generateValue: true
          - key: APP_URL
            value: https://laravel-react-app.onrender.com
          - key: LOG_CHANNEL
            value: stderr
          - key: DB_CONNECTION
            value: pgsql
          - key: DATABASE_URL
            fromDatabase:
                name: laravel_db
                property: connectionString
          - key: REDIS_URL
            fromService:
                type: redis
                name: laravel-redis
                property: connectionString

    - type: redis
      name: laravel-redis
      ipAllowList: []
      plan: free
      region: ohio

databases:
    - name: laravel_db
      ipAllowList: []
      plan: free
      region: ohio
